package com.example.domain

enum class Town() {
    AZCAPOTZALCO,
    ALVARO_OBREGON,
    BENITO_JUAREZ,
    COYOACAN,
    CUAJIMALPA_DE_MORELOS,
    CUAUHTEMOC,
    GUSTAVO_A_MADERO,
    IZTACALCO,
    IZTAPALAPA,
    MAGDALENA_CONTRERAS,
    MIGUEL_HIDALGO,
    MILPA_ALTA,
    TLALPAN,
    TLAHUAC,
    VENUSTIANO_CARRANZA,
    XOCHIMILCO;
}