version: "3.6"

services:
  app:
    build: ./
    container_name: mbdata
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ktor
      - POSTGRES_DB=mbdata
      - POSTGRES_PASSWORD=secret
    ports:
      - "54321:5432"
    expose:
      - 54321
    networks:
      - ktor-network
networks:
  ktor-network:
    driver: bridge